name: istart
description: A new Flutter project.

publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:


  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  slimy_card: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
      - assets/main_logo.png
      - assets/Rural Startup.png
      - assets/School Startup.png
      - assets/challenges.png
      - assets/start-up.png
