name: istart
description: A new Flutter project.

publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:


  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  slimy_card: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
      - assets/main_logo.png
      - assets/rural_startup.png
      - assets/school_startup.png
      - assets/challenges.png
      - assets/start_up.png
      - assets/more.png
      - assets/startups_banner.jpg

fonts:
  - family: Roboto
    fonts:
      -assets: assets/fonts/Roboto-Light.ttf